In [123]:
import pandas as pd

df = pd.read_csv('flights.csv')

In [124]:
df

,lastUpdatedAt,actualLandingTime,aircraftType,baggageClaim,codeshares,estimatedLandingTime,expectedTimeOnBelt,flightDirection,flightName,flightNumber,...,aircraftRegistration,checkinAllocations,expectedSecurityFilter,gate,pier,publicEstimatedOffBlockTime,expectedTimeBoarding,expectedTimeGateClosing,expectedTimeGateOpen,transferPositions
0,2025-07-30T03:13:09.080+02:00,2025-07-30T01:06:37.000+02:00,"{'iataMain': '32S', 'iataSub': '32Q'}",{'belts': ['4']},{'codeshares': ['KL2568']},2025-07-30T01:06:37.000+02:00,2025-07-30T02:13:09.000+02:00,A,HV5218,5218,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-07-30T01:44:21.092+02:00,2025-07-30T00:05:12.000+02:00,"{'iataMain': '32S', 'iataSub': '32Q'}",{'belts': ['2']},{'codeshares': ['KL3282']},2025-07-30T00:05:12.000+02:00,2025-07-30T00:38:38.000+02:00,A,HV5352,5352,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2025-07-30T03:13:09.080+02:00,2025-07-30T01:06:37.000+02:00,"{'iataMain': '32S', 'iataSub': '32Q'}",{'belts': ['4']},{'codeshares': ['KL2568']},2025-07-30T01:06:37.000+02:00,2025-07-30T02:13:09.000+02:00,A,KL2568,2568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2025-07-30T01:44:21.092+02:00,2025-07-30T00:05:12.000+02:00,"{'iataMain': '32S', 'iataSub': '32Q'}",{'belts': ['2']},{'codeshares': ['KL3282']},2025-07-30T00:05:12.000+02:00,2025-07-30T00:38:38.000+02:00,A,KL3282,3282,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2025-07-30T01:22:04.089+02:00,2025-07-29T23:55:21.000+02:00,"{'iataMain': '737', 'iataSub': '73H'}",{'belts': ['4']},{'codeshares': ['KL2751']},2025-07-29T23:55:21.000+02:00,2025-07-30T00:20:01.000+02:00,A,HV5462,5462,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4849,2025-07-29T14:44:29.688+02:00,NaN,"{'iataMain': 'EMJ', 'iataSub': 'E90'}",NaN,{'codeshares': ['G35521']},2025-07-30T23:32:00.000+02:00,NaN,A,G35521,5521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4850,2025-07-29T14:44:29.688+02:00,NaN,"{'iataMain': 'EMJ', 'iataSub': 'E90'}",NaN,{'codeshares': ['G35521']},2025-07-30T23:32:00.000+02:00,NaN,A,KL1568,1568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4851,2025-07-29T20:36:25.983+02:00,NaN,"{'iataMain': '737', 'iataSub': '73H'}",NaN,NaN,2025-07-30T23:37:00.000+02:00,NaN,A,HV5136,5136,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4852,2025-07-29T18:06:23.764+02:00,NaN,"{'iataMain': '74F', 'iataSub': '74Y'}",NaN,NaN,NaN,NaN,D,MP6121,6121,...,PHCKB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4853,2025-07-29T11:51:32.718+02:00,NaN,"{'iataMain': '32S', 'iataSub': '32Q'}",NaN,NaN,2025-07-30T23:42:00.000+02:00,NaN,A,HV5518,5518,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [125]:
type(df)

pandas.core.frame.DataFrame

Listar Colunas:

In [126]:
df.columns

Index(['lastUpdatedAt', 'actualLandingTime', 'aircraftType', 'baggageClaim',
       'codeshares', 'estimatedLandingTime', 'expectedTimeOnBelt',
       'flightDirection', 'flightName', 'flightNumber', 'id',
       'isOperationalFlight', 'mainFlight', 'prefixIATA', 'prefixICAO',
       'airlineCode', 'publicFlightState', 'route', 'scheduleDateTime',
       'scheduleDate', 'scheduleTime', 'serviceType', 'terminal',
       'schemaVersion', 'actualOffBlockTime', 'aircraftRegistration',
       'checkinAllocations', 'expectedSecurityFilter', 'gate', 'pier',
       'publicEstimatedOffBlockTime', 'expectedTimeBoarding',
       'expectedTimeGateClosing', 'expectedTimeGateOpen', 'transferPositions'],
      dtype='object')

Descrição numerica do dataframe

In [127]:
df.describe()

       flightNumber            id  airlineCode     terminal  schemaVersion
count   4854.000000  4.854000e+03  4850.000000  2553.000000         4854.0
mean    5074.754841  1.428877e+17   658.028454     1.515472            4.0
std     3292.446986  3.658901e+09  1318.127110     0.725066            0.0
min        1.000000  1.428877e+17    12.000000     1.000000            4.0
25%     1622.250000  1.428877e+17    80.000000     1.000000            4.0
50%     5673.000000  1.428877e+17   100.000000     1.000000            4.0
75%     8235.750000  1.428877e+17   289.000000     2.000000            4.0
max     9993.000000  1.428877e+17  5326.000000     4.000000            4.0

Descrição dos valores não numéricos (Categóricas)

In [128]:
df.describe(include='O')

,lastUpdatedAt,actualLandingTime,aircraftType,baggageClaim,codeshares,estimatedLandingTime,expectedTimeOnBelt,flightDirection,flightName,mainFlight,...,aircraftRegistration,checkinAllocations,expectedSecurityFilter,gate,pier,publicEstimatedOffBlockTime,expectedTimeBoarding,expectedTimeGateClosing,expectedTimeGateOpen,transferPositions
count,4854,52,4854,181,4384,2397,49,4854,4854,4854,...,2329,2372,1851,2348,2370,13,1864,1892,1880,126
unique,1446,33,41,15,976,323,30,2,4843,1438,...,403,494,5,121,8,8,160,154,151,3
top,2025-07-29T17:30:18.548+02:00,2025-07-30T05:14:13.000+02:00,"{'iataMain': '737', 'iataSub': '73H'}",{'belts': ['15']},"{'codeshares': ['AM6354', 'AZ3805', 'CZ7750', ...",2025-07-30T15:47:00.000+02:00,2025-07-30T05:49:55.835+02:00,A,DL9318,KL1220,...,PHAXF,{'checkinAllocations': [{'endTime': '2025-07-3...,VF1,D6,D,2025-07-30T07:00:00.000+02:00,2025-07-30T09:10:00.000+02:00,2025-07-30T20:20:00.000+02:00,2025-07-30T20:05:00.000+02:00,{'transferPositions': [3]}
freq,13,4,988,29,13,45,4,2430,2,13,...,32,38,1470,238,863,3,38,58,47,62

Obter mais informações:

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4854 entries, 0 to 4853
Data columns (total 35 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   lastUpdatedAt                4854 non-null   object
 1   actualLandingTime            52 non-null     object
 2   aircraftType                 4854 non-null   object
 3   baggageClaim                 181 non-null    object
 4   codeshares                   4384 non-null   object
 5   estimatedLandingTime         2397 non-null   object
 6   expectedTimeOnBelt           49 non-null     object
 7   flightDirection              4854 non-null   object
 8   flightName                   4854 non-null   object
 9   flightNumber                 4854 non-null   int64
 10  id                           4854 non-null   int64
 11  isOperationalFlight          4854 non-null   bool
 12  mainFlight                   4854 non-null   object
 13  prefixIATA                   4852 non-null   object
 14  prefixICAO                   4830 non-null   object
 15  airlineCode                  4850 non-null   float64
 16  publicFlightState            4854 non-null   object
 17  route                        4854 non-null   object
 18  scheduleDateTime             4854 non-null   object
 19  scheduleDate                 4854 non-null   object
 20  scheduleTime                 4854 non-null   object
 21  serviceType                  4854 non-null   object
 22  terminal                     2553 non-null   float64
 23  schemaVersion                4854 non-null   int64
 24  actualOffBlockTime           7 non-null      object
 25  aircraftRegistration         2329 non-null   object
 26  checkinAllocations           2372 non-null   object
 27  expectedSecurityFilter       1851 non-null   object
 28  gate                         2348 non-null   object
 29  pier                         2370 non-null   object
 30  publicEstimatedOffBlockTime  13 non-null     object
 31  expectedTimeBoarding         1864 non-null   object
 32  expectedTimeGateClosing      1892 non-null   object
 33  expectedTimeGateOpen         1880 non-null   object
 34  transferPositions            126 non-null    object
dtypes: bool(1), float64(2), int64(3), object(29)
memory usage: 1.3+ MB

Vamos estudar os modelos de avião que mais aparecem e as rotas mais fequentes

In [130]:
df.at[0, 'aircraftType']

"{'iataMain': '32S', 'iataSub': '32Q'}"

In [131]:
df["aircraftType"][1000]

"{'iataMain': '32S', 'iataSub': '319'}"

Vamos utilizar unma biblioteca que converte strings em dicionários

In [132]:
import ast

teste = ast.literal_eval(df["aircraftType"][0])
teste

{'iataMain': '32S', 'iataSub': '32Q'}

Uma forma de conververter todos os valores que estão na coluna "aircraftType"

In [133]:
for i in range(len(df)):
    df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])

C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["aircraftType"][i] = ast.literal_eval(df["aircraftType"][i])
C:\Users\marco\AppData\Local\Temp\ipykernel_8448\822957797.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:


In [134]:
df["aircraftType"][0]['iataMain']

'32S'

In [135]:
df["modeloAviao"] = None

In [136]:
# O valor que você quer atribuir
valor_a_atribuir = df["aircraftType"][0]['iataMain']

# Atribuição usando .loc[linha, coluna]
df.loc[0, "modeloAviao"] = valor_a_atribuir

In [137]:
df

,lastUpdatedAt,actualLandingTime,aircraftType,baggageClaim,codeshares,estimatedLandingTime,expectedTimeOnBelt,flightDirection,flightName,flightNumber,...,checkinAllocations,expectedSecurityFilter,gate,pier,publicEstimatedOffBlockTime,expectedTimeBoarding,expectedTimeGateClosing,expectedTimeGateOpen,transferPositions,modeloAviao
0,2025-07-30T03:13:09.080+02:00,2025-07-30T01:06:37.000+02:00,"{'iataMain': '32S', 'iataSub': '32Q'}",{'belts': ['4']},{'codeshares': ['KL2568']},2025-07-30T01:06:37.000+02:00,2025-07-30T02:13:09.000+02:00,A,HV5218,5218,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32S
1,2025-07-30T01:44:21.092+02:00,2025-07-30T00:05:12.000+02:00,"{'iataMain': '32S', 'iataSub': '32Q'}",{'belts': ['2']},{'codeshares': ['KL3282']},2025-07-30T00:05:12.000+02:00,2025-07-30T00:38:38.000+02:00,A,HV5352,5352,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,2025-07-30T03:13:09.080+02:00,2025-07-30T01:06:37.000+02:00,"{'iataMain': '32S', 'iataSub': '32Q'}",{'belts': ['4']},{'codeshares': ['KL2568']},2025-07-30T01:06:37.000+02:00,2025-07-30T02:13:09.000+02:00,A,KL2568,2568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,2025-07-30T01:44:21.092+02:00,2025-07-30T00:05:12.000+02:00,"{'iataMain': '32S', 'iataSub': '32Q'}",{'belts': ['2']},{'codeshares': ['KL3282']},2025-07-30T00:05:12.000+02:00,2025-07-30T00:38:38.000+02:00,A,KL3282,3282,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,2025-07-30T01:22:04.089+02:00,2025-07-29T23:55:21.000+02:00,"{'iataMain': '737', 'iataSub': '73H'}",{'belts': ['4']},{'codeshares': ['KL2751']},2025-07-29T23:55:21.000+02:00,2025-07-30T00:20:01.000+02:00,A,HV5462,5462,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4849,2025-07-29T14:44:29.688+02:00,NaN,"{'iataMain': 'EMJ', 'iataSub': 'E90'}",NaN,{'codeshares': ['G35521']},2025-07-30T23:32:00.000+02:00,NaN,A,G35521,5521,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4850,2025-07-29T14:44:29.688+02:00,NaN,"{'iataMain': 'EMJ', 'iataSub': 'E90'}",NaN,{'codeshares': ['G35521']},2025-07-30T23:32:00.000+02:00,NaN,A,KL1568,1568,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4851,2025-07-29T20:36:25.983+02:00,NaN,"{'iataMain': '737', 'iataSub': '73H'}",NaN,NaN,2025-07-30T23:37:00.000+02:00,NaN,A,HV5136,5136,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4852,2025-07-29T18:06:23.764+02:00,NaN,"{'iataMain': '74F', 'iataSub': '74Y'}",NaN,NaN,NaN,NaN,D,MP6121,6121,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4853,2025-07-29T11:51:32.718+02:00,NaN,"{'iataMain': '32S', 'iataSub': '32Q'}",NaN,NaN,2025-07-30T23:42:00.000+02:00,NaN,A,HV5518,5518,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None